ALTER TABLE `staff`
ADD `aadhaar_no` VARCHAR(255) NULL,
ADD `religion` VARCHAR(255) NULL,
ADD `caste` VARCHAR(255) NULL,
ADD `blood_group` VARCHAR(255) NULL,
ADD `country` VARCHAR(255) NULL,
ADD `state` VARCHAR(255) NULL,
ADD `pincode` VARCHAR(255) NULL,
ADD `is_visiting_faculty` TINYINT(1) NULL,
ADD `is_part_time_faculty` TINYINT(1) NULL,
ADD `is_full_time_faculty` TINYINT(1) NULL,
ADD `previous_salary` DECIMAL(10, 2) NULL,
ADD `uan_no` VARCHAR(255) NULL,
ADD `pan_no` VARCHAR(255) NULL,
ADD `previous_institution` VARCHAR(255) NULL,
ADD `subject_expertise` VARCHAR(255) NULL;
