CREATE TABLE `naac_c7_1_values_social_responsibilities` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `academic_year` VARCHAR(9) NOT NULL,
    `gender_equity_measures` TEXT,
    `disabled_friendly_campus_description` TEXT,
    `inclusive_environment_initiatives` TEXT,
    `human_values_ethics_activities` TEXT,
    `commemorative_events_details` TEXT,
    `alternate_energy_conservation_details` TEXT,
    `waste_management_details` TEXT,
    `water_conservation_details` TEXT,
    `green_campus_initiatives` TEXT,
    `quality_audits_environment_energy` TEXT,
    `code_of_conduct_details` TEXT,
    `document_link_gender_equity_policy` VARCHAR(255),
    `document_link_disabled_friendly_policy` VARCHAR(255),
    `document_link_environmental_audit` VARCHAR(255),
    `document_link_code_of_conduct` VARCHAR(255),
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);