#!/usr/bin/env python3
"""
maasc_import.py  —  Generate maasc_import.sql for production maasc instance.

Imports:
  - 3 departments (Chemistry, Mathematics, Tamil)
  - 7 classes + 2 sections + class_section links
  - 12 staff (from maasc/maasc_staff_clean.csv)
  - 131 students (from maasc/maasc_students_clean.csv)
  - student_session records (session_id=21 / 2025-26)
  - user accounts (staff, student, parent)

Run locally:
  cd /Applications/XAMPP/xamppfiles/htdocs/minerva
  python3 tools/maasc_import.py
  # then SCP + run on EC2 (printed at end)
"""

import csv
import os
import re
import subprocess
import sys

BASE      = '/Applications/XAMPP/xamppfiles/htdocs/minerva'
STAFF_CSV = f'{BASE}/maasc/maasc_staff_clean.csv'
STUDENT_CSV = f'{BASE}/maasc/maasc_students_clean.csv'
OUT_SQL   = f'{BASE}/tools/maasc_import.sql'

# ── DB constants ─────────────────────────────────────────────────────────────
SESSION_ID   = 21      # 2025-26
LANG_ID      = 4       # English
CURRENCY_ID  = 68      # INR
BATCH_TAG    = 'IMP_MAASC_2025'
BCRYPT_PW    = r'$2y$12$mUoUzS1Fgc0a.qsXU1jIf.V37EhCavy82beMW9K9Zd9lqFQ9NMgyK'  # Welcome@123

# ── Class → Section mapping (keys already normalised) ────────────────────────
CLASS_SECTION = {
    'II BBA':              'BBA',
    'III BBA':             'BBA',
    'II B.Sc Chemistry':   'A',
    'III CHEMISTRY':       'A',
    'II BA Tamil':         'A',
    'III MATHS':           'A',
}

# ── Class → Department mapping (keys are already normalised) ─────────────────
CLASS_DEPT = {
    'II B.Sc Chemistry':   'Chemistry',
    'III CHEMISTRY':       'Chemistry',
    'II BA Tamil':         'Tamil',
    'III MATHS':           'Mathematics',
    'II BBA':              None,
    'III BBA':             None,
}

# ── Staff role mapping (users.role string) ───────────────────────────────────
ROLE_MAP = {
    'assistant professor': ('Teacher', 2),
    'arts':                ('Teacher', 2),
    'accounts':            ('Accountant', 3),
    'teacher':             ('Teacher', 2),
    'principal':           ('Principal', 10),
    'hod':                 ('Teacher', 2),
}

# ── SQL helpers ───────────────────────────────────────────────────────────────
lines = []

def sql(s: str):
    lines.append(s)

def esc(s) -> str:
    """Escape value as SQL string (non-null)."""
    if s is None:
        return "''"
    s = str(s).strip()
    s = s.replace('\\', '\\\\').replace("'", "\\'")
    return f"'{s}'"

def esc_null(s) -> str:
    """Return SQL NULL for blank/None, else escaped string."""
    if s is None:
        return 'NULL'
    s = str(s).strip()
    if s.lower() in ('', 'none', 'nan', 'null'):
        return 'NULL'
    s = s.replace('\\', '\\\\').replace("'", "\\'")
    return f"'{s}'"

def fmt_date(s) -> str:
    """Return SQL date literal or NULL."""
    if not s:
        return 'NULL'
    s = str(s).strip()
    if re.match(r'^\d{4}-\d{2}-\d{2}$', s) and s != '0000-00-00':
        return f"'{s}'"
    return 'NULL'

def fmt_decimal(s, default='0.00') -> str:
    """Return decimal string for SQL."""
    try:
        if s is None or str(s).strip().lower() in ('', 'none', 'nan'):
            return default
        return f"{float(str(s).replace(',', '')):.2f}"
    except (ValueError, TypeError):
        return default

def norm_class(cls: str) -> str:
    """Normalise IIIMATHS → III MATHS etc."""
    cls = cls.strip()
    if cls.upper() == 'IIIMATHS':
        return 'III MATHS'
    return cls

# ═══════════════════════════════════════════════════════════════════════════════
# HEADER
# ═══════════════════════════════════════════════════════════════════════════════
sql("-- ============================================================")
sql("-- maasc_import.sql  —  generated by tools/maasc_import.py")
sql("-- Institution: MAASC   DB: maasc   Session: 2025-26 (id=21)")
sql(f"-- Batch tag: {BATCH_TAG}")
sql("-- ============================================================")
sql("SET NAMES utf8mb4;")
sql("SET FOREIGN_KEY_CHECKS = 0;")
sql("")

# ═══════════════════════════════════════════════════════════════════════════════
# 1. DEPARTMENTS
# ═══════════════════════════════════════════════════════════════════════════════
sql("-- ── 1. Departments ────────────────────────────────────────────────────")
for dept in ['Chemistry', 'Mathematics', 'Tamil']:
    sql(f"INSERT INTO department (department_name, is_active) "
        f"SELECT {esc(dept)}, 1 "
        f"WHERE NOT EXISTS (SELECT 1 FROM department WHERE LOWER(department_name)=LOWER({esc(dept)}));")
sql("")

# ═══════════════════════════════════════════════════════════════════════════════
# 2. DESIGNATIONS (create 'Arts' if missing)
# ═══════════════════════════════════════════════════════════════════════════════
sql("-- ── 2. Designations (add Arts if not present) ────────────────────────")
sql("INSERT INTO staff_designation (designation, is_active) "
    "SELECT 'Arts', 'yes' "
    "WHERE NOT EXISTS (SELECT 1 FROM staff_designation WHERE LOWER(designation)='arts');")
sql("")

# ═══════════════════════════════════════════════════════════════════════════════
# 3. CLASSES
# ═══════════════════════════════════════════════════════════════════════════════
sql("-- ── 3. Classes ────────────────────────────────────────────────────────")
for cls, dept in CLASS_DEPT.items():
    cls_norm = norm_class(cls)
    if dept:
        dept_sql = f"(SELECT id FROM department WHERE LOWER(department_name)=LOWER({esc(dept)}) LIMIT 1)"
    else:
        dept_sql = "NULL"
    sql(f"INSERT INTO classes (class, department_id, is_active, class_type) "
        f"SELECT {esc(cls_norm)}, {dept_sql}, 'yes', 'academic' "
        f"WHERE NOT EXISTS (SELECT 1 FROM classes WHERE LOWER(class)=LOWER({esc(cls_norm)}));")
sql("")

# ═══════════════════════════════════════════════════════════════════════════════
# 4. SECTIONS
# ═══════════════════════════════════════════════════════════════════════════════
sql("-- ── 4. Sections ───────────────────────────────────────────────────────")
for sec in sorted(set(CLASS_SECTION.values())):
    sql(f"INSERT INTO sections (section, is_active) "
        f"SELECT {esc(sec)}, 'yes' "
        f"WHERE NOT EXISTS (SELECT 1 FROM sections WHERE LOWER(section)=LOWER({esc(sec)}));")
sql("")

# ═══════════════════════════════════════════════════════════════════════════════
# 5. CLASS_SECTIONS
# ═══════════════════════════════════════════════════════════════════════════════
sql("-- ── 5. Class-Section links ────────────────────────────────────────────")
# Use normalised class names (de-dup)
seen_class_sec = set()
for cls, sec in CLASS_SECTION.items():
    cls_norm = norm_class(cls)
    key = (cls_norm, sec)
    if key in seen_class_sec:
        continue
    seen_class_sec.add(key)
    sql(f"INSERT INTO class_sections (class_id, section_id, is_active) "
        f"SELECT c.id, s.id, 'yes' "
        f"FROM classes c, sections s "
        f"WHERE LOWER(c.class)=LOWER({esc(cls_norm)}) "
        f"AND LOWER(s.section)=LOWER({esc(sec)}) "
        f"AND NOT EXISTS ("
        f"  SELECT 1 FROM class_sections cs2 "
        f"  JOIN classes cc ON cc.id=cs2.class_id "
        f"  JOIN sections ss ON ss.id=cs2.section_id "
        f"  WHERE LOWER(cc.class)=LOWER({esc(cls_norm)}) AND LOWER(ss.section)=LOWER({esc(sec)})"
        f");")
sql("")

# ═══════════════════════════════════════════════════════════════════════════════
# 6. STAFF
# ═══════════════════════════════════════════════════════════════════════════════
sql("-- ── 6. Staff ──────────────────────────────────────────────────────────")

with open(STAFF_CSV, newline='', encoding='utf-8-sig') as f:
    staff_rows = list(csv.DictReader(f))

staff_emp_ids = []

for r in staff_rows:
    emp_id       = r.get('employee_id', '').strip()
    biometric_id = r.get('biometric_id', '').strip() or None
    name         = r.get('name', '').strip()
    surname      = r.get('surname', '').strip()
    prefix       = r.get('prefix', '').strip()
    father_name  = r.get('father_name', '').strip()
    mother_name  = r.get('mother_name', '').strip()
    contact_no   = r.get('contact_no', '').strip()
    emg_contact  = r.get('emergency_contact_no', '').strip()
    email        = r.get('email', '').strip()
    dob          = r.get('dob', '').strip()
    marital      = r.get('marital_status', '').strip()
    doj          = r.get('date_of_joining', '').strip()
    dol          = r.get('date_of_leaving', '').strip()
    local_addr   = r.get('local_address', '').strip()
    perm_addr    = r.get('permanent_address', '').strip()
    gender       = r.get('gender', '').strip()
    qual         = r.get('qualification', '').strip()
    work_exp     = r.get('work_exp', '').strip()
    bank_acct    = r.get('bank_account_no', '').strip()
    bank_name    = r.get('bank_name', '').strip()
    ifsc         = r.get('ifsc_code', '').strip()
    bank_branch  = r.get('bank_branch', '').strip()
    acct_title   = r.get('account_title', '').strip()
    payscale     = r.get('payscale', '').strip()
    basic_sal    = fmt_decimal(r.get('basic_salary', ''))
    uan_no       = r.get('uan_no', '').strip() or None
    esi_no       = r.get('esi_no', '').strip() or None
    pan_no       = r.get('pan_no', '').strip() or None
    contract_type= r.get('contract_type', '').strip()
    shift        = r.get('shift', 'Day').strip()
    location     = r.get('location', '').strip()
    aadhaar      = r.get('aadhaar_no', '').strip() or None
    religion     = r.get('religion', '').strip() or None
    caste        = r.get('caste', '').strip() or None
    blood_group  = r.get('blood_group', '').strip() or None
    country      = r.get('country', '').strip() or None
    state        = r.get('state', '').strip() or None
    pincode      = r.get('pincode', '').strip() or None
    prev_inst    = r.get('previous_institution', '').strip() or None
    prev_sal     = r.get('previous_salary', '').strip() or None
    subj_exp     = r.get('subject_expertise', '').strip() or None
    subj_spec    = r.get('subject_specialization', '').strip() or None
    ug_qual      = r.get('ug_qualification', '').strip() or None
    pg_qual      = r.get('pg_qualification', '').strip() or None
    higher_qual  = r.get('higher_qualification', '').strip() or None
    category_id  = r.get('category_id', '').strip() or None
    dept_name    = r.get('department', '').strip()
    desig_name   = r.get('designation', '').strip()
    role_str     = r.get('role', '').strip()

    if not emp_id or not name:
        continue

    staff_emp_ids.append((emp_id, desig_name, role_str))

    dept_id_sql = (
        f"(SELECT id FROM department WHERE LOWER(department_name)=LOWER({esc(dept_name)}) LIMIT 1)"
        if dept_name else "NULL"
    )
    desig_id_sql = (
        f"(SELECT id FROM staff_designation WHERE LOWER(designation)=LOWER({esc(desig_name)}) LIMIT 1)"
        if desig_name else "NULL"
    )

    sql(f"-- Staff: {name}")
    sql(f"INSERT INTO staff ("
        f"employee_id, biometric_id, lang_id, currency_id, "
        f"department, designation, "
        f"prefix, ug_qualification, pg_qualification, higher_qualification, "
        f"subject_specialization, subject_expertise, "
        f"qualification, work_exp, "
        f"name, surname, father_name, mother_name, "
        f"contact_no, emergency_contact_no, emergency_contact_number, "
        f"email, dob, marital_status, date_of_joining, date_of_leaving, "
        f"local_address, permanent_address, "
        f"gender, "
        f"account_title, bank_account_no, bank_name, ifsc_code, bank_branch, "
        f"payscale, basic_salary, uan_no, esi_no, pan_no, "
        f"contract_type, shift, location, "
        f"aadhaar_no, religion, caste, blood_group, country, state, pincode, "
        f"previous_salary, previous_institution, "
        f"note, image, password, is_active, user_id, verification_code, "
        f"facebook, twitter, linkedin, instagram, "
        f"resume, joining_letter, resignation_letter, "
        f"other_document_name, other_document_file"
        f")"
        f" SELECT "
        f"{esc(emp_id)}, {esc_null(biometric_id)}, {LANG_ID}, {CURRENCY_ID}, "
        f"{dept_id_sql}, {desig_id_sql}, "
        f"{esc(prefix)}, {esc_null(ug_qual)}, {esc_null(pg_qual)}, {esc_null(higher_qual)}, "
        f"{esc_null(subj_spec)}, {esc_null(subj_exp)}, "
        f"{esc(qual)}, {esc(work_exp)}, "
        f"{esc(name)}, {esc(surname)}, {esc(father_name)}, {esc(mother_name)}, "
        f"{esc(contact_no)}, {esc(emg_contact)}, {esc(emg_contact)}, "
        f"{esc(email)}, {fmt_date(dob)}, {esc(marital)}, {fmt_date(doj)}, {fmt_date(dol)}, "
        f"{esc(local_addr)}, {esc(perm_addr)}, "
        f"{esc(gender)}, "
        f"{esc(acct_title)}, {esc(bank_acct)}, {esc(bank_name)}, {esc(ifsc)}, {esc(bank_branch)}, "
        f"{esc(payscale)}, {basic_sal}, {esc_null(uan_no)}, {esc_null(esi_no)}, {esc_null(pan_no)}, "
        f"{esc(contract_type)}, {esc(shift)}, {esc(location)}, "
        f"{esc_null(aadhaar)}, {esc_null(religion)}, {esc_null(caste)}, {esc_null(blood_group)}, "
        f"{esc_null(country)}, {esc_null(state)}, {esc_null(pincode)}, "
        f"{esc_null(fmt_decimal(prev_sal) if prev_sal else None)}, {esc_null(prev_inst)}, "
        f"{esc(BATCH_TAG)}, '', {esc(BCRYPT_PW)}, 1, 0, '', "
        f"'', '', '', '', "
        f"'', '', '', "
        f"'', '' "
        f"WHERE NOT EXISTS (SELECT 1 FROM staff WHERE employee_id={esc(emp_id)});"
    )
sql("")

# ── Staff user accounts ──────────────────────────────────────────────────────
sql("-- ── 6b. Staff user accounts ───────────────────────────────────────────")
for emp_id, desig_name, role_str in staff_emp_ids:
    lookup_key = role_str.lower() if role_str else desig_name.lower()
    user_role, role_id = ROLE_MAP.get(lookup_key, ROLE_MAP.get(desig_name.lower(), ('Teacher', 2)))
    sql(f"INSERT INTO users (user_id, username, password, childs, role, lang_id, currency_id, verification_code, is_active)"
        f" SELECT s.id, {esc(emp_id)}, 'Welcome@123', '', {esc(user_role)}, {LANG_ID}, {CURRENCY_ID}, '', 'yes'"
        f" FROM staff s WHERE s.employee_id={esc(emp_id)}"
        f" AND NOT EXISTS (SELECT 1 FROM users u WHERE u.username={esc(emp_id)} AND u.role={esc(user_role)});")
sql("")

# ── Update staff.user_id ─────────────────────────────────────────────────────
sql("-- ── 6c. Link staff.user_id → users.id ───────────────────────────────")
for emp_id, desig_name, role_str in staff_emp_ids:
    lookup_key = role_str.lower() if role_str else desig_name.lower()
    user_role, _ = ROLE_MAP.get(lookup_key, ROLE_MAP.get(desig_name.lower(), ('Teacher', 2)))
    sql(f"UPDATE staff s "
        f"JOIN users u ON u.username={esc(emp_id)} AND u.role={esc(user_role)} "
        f"SET s.user_id=u.id "
        f"WHERE s.employee_id={esc(emp_id)} AND s.user_id=0;")
sql("")

# ── Staff roles ──────────────────────────────────────────────────────────────
sql("-- ── 6d. Staff roles ──────────────────────────────────────────────────")
for emp_id, desig_name, role_str in staff_emp_ids:
    lookup_key = role_str.lower() if role_str else desig_name.lower()
    _, role_id = ROLE_MAP.get(lookup_key, ROLE_MAP.get(desig_name.lower(), ('Teacher', 2)))
    sql(f"INSERT IGNORE INTO staff_roles (staff_id, role_id, is_active)"
        f" SELECT s.id, {role_id}, 1 FROM staff s"
        f" WHERE s.employee_id={esc(emp_id)};")
sql("")

# ═══════════════════════════════════════════════════════════════════════════════
# 7. STUDENTS
# ═══════════════════════════════════════════════════════════════════════════════
sql("-- ── 7. Students ──────────────────────────────────────────────────────")

with open(STUDENT_CSV, newline='', encoding='utf-8-sig') as f:
    student_rows = list(csv.DictReader(f))

student_adm_nos = []

for r in student_rows:
    adm_no       = r.get('admission_no', '').strip()
    roll_no      = r.get('roll_no', '').strip()
    cls_raw      = r.get('class', '').strip()
    cls          = norm_class(cls_raw)
    firstname    = r.get('firstname', '').strip()
    middlename   = r.get('middlename', '').strip() or None
    lastname     = r.get('lastname', '').strip() or None
    gender       = r.get('gender', '').strip()
    dob          = r.get('dob', '').strip()
    category_id  = r.get('category_id', '').strip() or None
    religion     = r.get('religion', '').strip() or None
    cast_val     = r.get('cast', '').strip() or None
    mobileno     = r.get('mobileno', '').strip() or None
    email        = r.get('email', '').strip() or None
    adm_date     = r.get('admission_date', '').strip()
    blood_group  = r.get('blood_group', '').strip()
    height       = r.get('height', '').strip() or ''
    weight       = r.get('weight', '').strip() or ''
    meas_date    = r.get('measurement_date', '').strip()
    father_name  = r.get('father_name', '').strip() or None
    father_phone = r.get('father_phone', '').strip() or None
    father_occ   = r.get('father_occupation', '').strip() or None
    mother_name  = r.get('mother_name', '').strip() or None
    mother_phone = r.get('mother_phone', '').strip() or None
    mother_occ   = r.get('mother_occupation', '').strip() or None
    gdn_is       = r.get('guardian_is', 'father').strip() or 'father'
    gdn_name     = r.get('guardian_name', '').strip() or None
    gdn_rel      = r.get('guardian_relation', '').strip() or None
    gdn_email    = r.get('guardian_email', '').strip() or None
    gdn_phone    = r.get('guardian_phone', '').strip() or None
    gdn_occ      = r.get('guardian_occupation', '').strip() or None
    gdn_addr     = r.get('guardian_address', '').strip() or None
    cur_addr     = r.get('current_address', '').strip() or None
    perm_addr    = r.get('permanent_address', '').strip() or None
    bank_acct    = r.get('bank_account_no', '').strip() or None
    bank_name    = r.get('bank_name', '').strip() or None
    ifsc         = r.get('ifsc_code', '').strip() or None
    aadhaar      = r.get('adhar_no', '').strip() or None
    prev_school  = r.get('previous_school', '').strip() or None
    reg_no       = r.get('register_no', '').strip() or None
    reg_id       = r.get('regulation_id', '').strip() or None
    emis_num     = r.get('emis_num', '').strip() or None
    hsc_reg      = r.get('hsc_reg_no', '').strip() or None
    ug_reg       = r.get('ug_reg_no', '').strip() or None
    abc_id       = r.get('abc_id', '').strip() or None
    father_adhar = r.get('father_adhar_no', '').strip() or None
    mother_adhar = r.get('mother_adhar_no', '').strip() or None
    migr_cert    = r.get('migration_cert_num', '').strip() or None
    medium       = r.get('medium', '').strip() or None
    rte          = r.get('rte', '').strip() or None
    samagra_id   = r.get('samagra_id', '').strip() or None

    if not adm_no or not firstname:
        continue

    student_adm_nos.append((adm_no, cls))

    sql(f"-- Student: {firstname} ({cls})")
    sql(f"INSERT INTO students ("
        f"admission_no, roll_no, firstname, middlename, lastname, "
        f"gender, dob, category_id, religion, cast, "
        f"mobileno, email, admission_date, blood_group, "
        f"height, weight, measurement_date, "
        f"father_name, father_phone, father_occupation, "
        f"mother_name, mother_phone, mother_occupation, "
        f"guardian_is, guardian_name, guardian_relation, guardian_email, "
        f"guardian_phone, guardian_occupation, guardian_address, "
        f"current_address, permanent_address, "
        f"bank_account_no, bank_name, ifsc_code, "
        f"adhar_no, father_adhar_no, mother_adhar_no, "
        f"register_no, regulation_id, emis_num, hsc_reg_no, ug_reg_no, "
        f"abc_id, migration_cert_num, medium, samagra_id, rte, "
        f"previous_school, "
        f"is_active, parent_id, dis_note, father_pic, mother_pic, guardian_pic, "
        f"note"
        f")"
        f" SELECT "
        f"{esc(adm_no)}, {esc_null(roll_no)}, {esc(firstname)}, {esc_null(middlename)}, {esc_null(lastname)}, "
        f"{esc(gender)}, {fmt_date(dob)}, {esc_null(category_id)}, {esc_null(religion)}, {esc_null(cast_val)}, "
        f"{esc_null(mobileno)}, {esc_null(email)}, {fmt_date(adm_date)}, {esc(blood_group)}, "
        f"{esc(height)}, {esc(weight)}, {fmt_date(meas_date)}, "
        f"{esc_null(father_name)}, {esc_null(father_phone)}, {esc_null(father_occ)}, "
        f"{esc_null(mother_name)}, {esc_null(mother_phone)}, {esc_null(mother_occ)}, "
        f"{esc(gdn_is)}, {esc_null(gdn_name)}, {esc_null(gdn_rel)}, {esc_null(gdn_email)}, "
        f"{esc_null(gdn_phone)}, {esc(gdn_occ or '')}, {esc_null(gdn_addr)}, "
        f"{esc_null(cur_addr)}, {esc_null(perm_addr)}, "
        f"{esc_null(bank_acct)}, {esc_null(bank_name)}, {esc_null(ifsc)}, "
        f"{esc_null(aadhaar)}, {esc_null(father_adhar)}, {esc_null(mother_adhar)}, "
        f"{esc_null(reg_no)}, {esc_null(reg_id)}, {esc_null(emis_num)}, {esc_null(hsc_reg)}, {esc_null(ug_reg)}, "
        f"{esc_null(abc_id)}, {esc_null(migr_cert)}, {esc_null(medium)}, {esc_null(samagra_id)}, {esc_null(rte)}, "
        f"{esc_null(prev_school)}, "
        f"'yes', 0, '', '', '', '', "
        f"{esc(BATCH_TAG)} "
        f"WHERE NOT EXISTS (SELECT 1 FROM students WHERE admission_no={esc(adm_no)});"
    )

sql("")

# ═══════════════════════════════════════════════════════════════════════════════
# 8. STUDENT SESSIONS
# ═══════════════════════════════════════════════════════════════════════════════
sql("-- ── 8. Student sessions ──────────────────────────────────────────────")

# Unique classes in import
unique_classes = sorted(set(norm_class(c) for _, c in student_adm_nos))

for cls in unique_classes:
    sec = CLASS_SECTION.get(cls, 'A')
    sql(f"-- {cls} → section {sec}")
    sql(f"INSERT INTO student_session (session_id, student_id, class_id, section_id, is_active, is_alumni)")
    sql(f"  SELECT {SESSION_ID}, s.id, cs.class_id, cs.section_id, 'yes', 0")
    sql(f"  FROM students s")
    sql(f"  JOIN classes c ON LOWER(c.class)=LOWER({esc(cls)})")
    sql(f"  JOIN sections sec ON LOWER(sec.section)=LOWER({esc(sec)})")
    sql(f"  JOIN class_sections cs ON cs.class_id=c.id AND cs.section_id=sec.id")
    sql(f"  WHERE s.note={esc(BATCH_TAG)} AND s.admission_no IN (")
    cls_adm_nos = [adm_no for adm_no, c in student_adm_nos if norm_class(c) == cls]
    sql(f"    {', '.join(esc(a) for a in cls_adm_nos)}")
    sql(f"  )")
    sql(f"  AND NOT EXISTS (")
    sql(f"    SELECT 1 FROM student_session ss2")
    sql(f"    WHERE ss2.session_id={SESSION_ID} AND ss2.student_id=s.id")
    sql(f"  );")
    sql("")

# ═══════════════════════════════════════════════════════════════════════════════
# 9. STUDENT USER ACCOUNTS
# ═══════════════════════════════════════════════════════════════════════════════
sql("-- ── 9. Student user accounts ─────────────────────────────────────────")
sql("INSERT INTO users (user_id, username, password, childs, role, lang_id, currency_id, verification_code, is_active)")
sql(f"SELECT s.id, CONCAT('std', s.id), 'Welcome@123', '', 'student', {LANG_ID}, {CURRENCY_ID}, '', 'yes'")
sql(f"FROM students s WHERE s.note={esc(BATCH_TAG)}")
sql("AND NOT EXISTS (SELECT 1 FROM users u WHERE u.user_id=s.id AND u.role='student');")
sql("")

sql("-- Parent user accounts")
sql("INSERT INTO users (user_id, username, password, childs, role, lang_id, currency_id, verification_code, is_active)")
sql(f"SELECT s.id, CONCAT('par', s.id), 'Welcome@123', s.id, 'parent', {LANG_ID}, {CURRENCY_ID}, '', 'yes'")
sql(f"FROM students s WHERE s.note={esc(BATCH_TAG)}")
sql("AND NOT EXISTS (SELECT 1 FROM users u WHERE u.username=CONCAT('par', s.id) AND u.role='parent');")
sql("")

sql("-- Set parent_id on students")
sql(f"UPDATE students s")
sql(f"JOIN users u ON u.username=CONCAT('par', s.id) AND u.role='parent'")
sql(f"SET s.parent_id=u.id")
sql(f"WHERE s.note={esc(BATCH_TAG)};")
sql("")

sql("SET FOREIGN_KEY_CHECKS = 1;")
sql("-- ── End of maasc_import.sql ────────────────────────────────────────────")

# ═══════════════════════════════════════════════════════════════════════════════
# WRITE SQL FILE
# ═══════════════════════════════════════════════════════════════════════════════
with open(OUT_SQL, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')

print(f"SQL file written: {OUT_SQL}")
print(f"  Staff rows:   {len(staff_rows)}")
print(f"  Student rows: {len(student_rows)}")
print(f"  Unique classes: {unique_classes}")
print()
print("To deploy:")
PEM  = "/Volumes/WORK/aws ec2 connect/minerva_prod.pem"
HOST = "ec2-user@13.234.255.106"
print(f"  scp -i '{PEM}' {OUT_SQL} {HOST}:/tmp/maasc_import.sql")
print(f"  ssh -i '{PEM}' {HOST} \"mysql -u meenakshi -p'3gw4*86*!zno-EMO' maasc < /tmp/maasc_import.sql\"")

# ── Optionally auto-deploy ────────────────────────────────────────────────────
if '--deploy' in sys.argv:
    print("\nDeploying to EC2...")
    r1 = subprocess.run(['scp', '-i', PEM, '-o', 'StrictHostKeyChecking=no',
                         OUT_SQL, f'{HOST}:/tmp/maasc_import.sql'],
                        capture_output=True, text=True)
    if r1.returncode != 0:
        print("SCP failed:", r1.stderr)
        sys.exit(1)
    print("SCP OK. Running SQL...")
    r2 = subprocess.run(['ssh', '-i', PEM, '-o', 'StrictHostKeyChecking=no', HOST,
                         f"mysql -u meenakshi -p'3gw4*86*!zno-EMO' maasc < /tmp/maasc_import.sql"],
                        capture_output=True, text=True)
    if r2.returncode != 0:
        print("MySQL failed:", r2.stderr)
        sys.exit(1)
    print("Done! MySQL output:", r2.stdout or "(no output = success)")
