#!/usr/bin/env python3
"""
maptc_import.py  —  Generate maptc_import.sql for production maptc instance.

Imports:
  - 11 classes + 1 section (A) + class_section links
  - 412 students (from 'maptc - Student details.xlsx')
  - student_session records (session_id=22 / 2026-27)
  - user accounts (student, parent)

Run locally:
  cd /Applications/XAMPP/xamppfiles/htdocs/minerva
  python3 tools/maptc_import.py
  # then SCP + run on EC2 (printed at end)

  To auto-deploy:
  python3 tools/maptc_import.py --deploy
"""

import os
import re
import subprocess
import sys
from datetime import datetime

try:
    import openpyxl
except ImportError:
    print("ERROR: openpyxl not installed. Run: pip install openpyxl")
    sys.exit(1)

BASE        = '/Applications/XAMPP/xamppfiles/htdocs/minerva'
STUDENT_XLS = f'{BASE}/maptc - Student details.xlsx'
OUT_SQL     = f'{BASE}/tools/maptc_import.sql'

# ── DB constants ─────────────────────────────────────────────────────────────
SESSION_ID  = 22     # 2026-27
LANG_ID     = 4      # English
CURRENCY_ID = 68     # INR
BATCH_TAG   = 'IMP_MAPTC_2026'
BCRYPT_PW   = r'$2y$12$mUoUzS1Fgc0a.qsXU1jIf.V37EhCavy82beMW9K9Zd9lqFQ9NMgyK'  # Welcome@123

# ── Class → Section mapping ───────────────────────────────────────────────────
# DB class name = "{roman} {dept.title()}"  e.g. "III Civil"
# DB section    = always "A"
CLASS_SECTION = {
    'II CIVIL':  'A',
    'II CT':     'A',
    'II ECE':    'A',
    'II EEE':    'A',
    'II IT':     'A',
    'II MECH':   'A',
    'III CIVIL': 'A',
    'III CT':    'A',
    'III ECE':   'A',
    'III EEE':   'A',
    'III MECH':  'A',
}

# ── SQL helpers ───────────────────────────────────────────────────────────────
lines = []

def sql(s: str):
    lines.append(s)

def esc(s) -> str:
    """Escape value as SQL string (non-null)."""
    if s is None:
        return "''"
    s = str(s).strip()
    s = s.replace('\\', '\\\\').replace("'", "\\'")
    return f"'{s}'"

def esc_null(s) -> str:
    """Return SQL NULL for blank/None, else escaped string."""
    if s is None:
        return 'NULL'
    s = str(s).strip()
    if s.lower() in ('', 'none', 'nan', 'null'):
        return 'NULL'
    s = s.replace('\\', '\\\\').replace("'", "\\'")
    return f"'{s}'"

def fmt_date(s) -> str:
    """Return SQL date literal or NULL. Handles YYYY-MM-DD and DD.MM.YYYY formats."""
    if not s:
        return 'NULL'
    if isinstance(s, datetime):
        return f"'{s.strftime('%Y-%m-%d')}'"
    s = str(s).strip()
    if not s or s.lower() in ('none', 'nan', 'null', ''):
        return 'NULL'
    # YYYY-MM-DD
    if re.match(r'^\d{4}-\d{2}-\d{2}$', s) and s != '0000-00-00':
        return f"'{s}'"
    # DD.MM.YYYY
    m = re.match(r'^(\d{1,2})\.(\d{1,2})\.(\d{4})$', s)
    if m:
        d, mo, y = m.groups()
        return f"'{y}-{mo.zfill(2)}-{d.zfill(2)}'"
    # datetime string (openpyxl may produce these)
    for fmt in ('%Y-%m-%d %H:%M:%S', '%d-%m-%Y', '%d/%m/%Y'):
        try:
            return f"'{datetime.strptime(s, fmt).strftime('%Y-%m-%d')}'"
        except ValueError:
            pass
    return 'NULL'

def make_class_name(class_col, section_col) -> str:
    """Build DB class name: '{roman} {dept.upper()}' e.g. 'III CIVIL'."""
    return f"{str(class_col).strip().upper()} {str(section_col).strip().upper()}"

def clean_mobile(s) -> str:
    """Convert numeric or string mobile to clean 10-digit string."""
    if s is None:
        return None
    try:
        val = str(int(float(str(s)))).strip()
        return val if val and val not in ('0', 'nan') else None
    except (ValueError, TypeError):
        val = str(s).strip()
        return val if val else None

# ═══════════════════════════════════════════════════════════════════════════════
# LOAD EXCEL
# ═══════════════════════════════════════════════════════════════════════════════
wb = openpyxl.load_workbook(STUDENT_XLS, data_only=True)
ws = wb.active

headers = [str(cell.value).strip() if cell.value is not None else '' for cell in ws[1]]

student_rows = []
for row in ws.iter_rows(min_row=2, values_only=True):
    if all(v is None for v in row):
        continue
    student_rows.append(dict(zip(headers, row)))

print(f"Loaded {len(student_rows)} student rows from Excel.")

# ═══════════════════════════════════════════════════════════════════════════════
# HEADER
# ═══════════════════════════════════════════════════════════════════════════════
sql("-- ============================================================")
sql("-- maptc_import.sql  —  generated by tools/maptc_import.py")
sql("-- Institution: MAPTC   DB: maptc   Session: 2026-27 (id=22)")
sql(f"-- Batch tag: {BATCH_TAG}")
sql("-- ============================================================")
sql("SET NAMES utf8mb4;")
sql("SET FOREIGN_KEY_CHECKS = 0;")
sql("")

# ═══════════════════════════════════════════════════════════════════════════════
# 1. CLASSES
# ═══════════════════════════════════════════════════════════════════════════════
sql("-- ── 1. Classes ────────────────────────────────────────────────────────")
for cls in CLASS_SECTION:
    sql(f"INSERT INTO classes (class, department_id, is_active, class_type) "
        f"SELECT {esc(cls)}, NULL, 'yes', 'academic' "
        f"WHERE NOT EXISTS (SELECT 1 FROM classes WHERE LOWER(class)=LOWER({esc(cls)}));")
sql("")

# ═══════════════════════════════════════════════════════════════════════════════
# 2. SECTIONS
# ═══════════════════════════════════════════════════════════════════════════════
sql("-- ── 2. Sections ───────────────────────────────────────────────────────")
sql("INSERT INTO sections (section, is_active) "
    "SELECT 'A', 'yes' "
    "WHERE NOT EXISTS (SELECT 1 FROM sections WHERE LOWER(section)='a');")
sql("")

# ═══════════════════════════════════════════════════════════════════════════════
# 3. CLASS_SECTIONS
# ═══════════════════════════════════════════════════════════════════════════════
sql("-- ── 3. Class-Section links ────────────────────────────────────────────")
for cls, sec in CLASS_SECTION.items():
    sql(f"INSERT INTO class_sections (class_id, section_id, is_active) "
        f"SELECT c.id, s.id, 'yes' "
        f"FROM classes c, sections s "
        f"WHERE LOWER(c.class)=LOWER({esc(cls)}) "
        f"AND LOWER(s.section)=LOWER({esc(sec)}) "
        f"AND NOT EXISTS ("
        f"  SELECT 1 FROM class_sections cs2 "
        f"  JOIN classes cc ON cc.id=cs2.class_id "
        f"  JOIN sections ss ON ss.id=cs2.section_id "
        f"  WHERE LOWER(cc.class)=LOWER({esc(cls)}) AND LOWER(ss.section)=LOWER({esc(sec)})"
        f");")
sql("")

# ═══════════════════════════════════════════════════════════════════════════════
# 4. STUDENTS
# ═══════════════════════════════════════════════════════════════════════════════
sql("-- ── 4. Students ──────────────────────────────────────────────────────")

student_keys = []   # list of (admission_no_used, cls_name) for session/user steps

for r in student_rows:
    class_col   = r.get('class', '')
    section_col = r.get('section', '')
    cls         = make_class_name(class_col, section_col)

    reg_no      = r.get('register_no', '')
    reg_no      = str(int(float(str(reg_no)))).strip() if reg_no not in (None, '', 'None') else ''

    adm_no_raw  = r.get('admission_no', None)
    if adm_no_raw not in (None, '', 'None') and str(adm_no_raw).strip().lower() not in ('none', 'nan'):
        adm_no = str(adm_no_raw).strip()
    else:
        adm_no = reg_no   # fall back to register_no

    if not adm_no and not reg_no:
        print(f"  SKIP row with no admission_no or register_no: {r.get('firstname')}")
        continue

    roll_no      = r.get('roll_no', '')
    if roll_no not in (None, '', 'None'):
        try:
            roll_no = str(int(float(str(roll_no))))
        except (ValueError, TypeError):
            roll_no = str(roll_no).strip()
    else:
        roll_no = None

    firstname    = str(r.get('firstname', '') or '').strip()
    middlename   = str(r.get('middlename', '') or '').strip() or None
    lastname     = str(r.get('lastname', '') or '').strip() or None
    gender       = str(r.get('gender', '') or '').strip()
    dob          = fmt_date(r.get('dob'))
    category_id  = r.get('category_id')
    if category_id not in (None, '', 'None'):
        try:
            category_id = str(int(float(str(category_id))))
        except (ValueError, TypeError):
            category_id = str(category_id).strip() or None
    else:
        category_id = None
    religion     = str(r.get('religion', '') or '').strip() or None
    cast_val     = str(r.get('cast', '') or '').strip() or None
    mobileno     = clean_mobile(r.get('mobileno'))
    email_raw    = r.get('email')
    email        = str(email_raw).strip() if email_raw not in (None, '', 'None') else None
    adm_date     = fmt_date(r.get('admission_date'))
    blood_group  = str(r.get('blood_group', '') or '').strip()
    height       = str(r.get('height', '') or '').strip()
    weight       = str(r.get('weight', '') or '').strip()
    meas_date    = fmt_date(r.get('measurement_date'))
    father_name  = str(r.get('father_name', '') or '').strip() or None
    father_phone = clean_mobile(r.get('father_phone'))
    father_occ   = str(r.get('father_occupation', '') or '').strip() or None
    mother_name  = str(r.get('mother_name', '') or '').strip() or None
    mother_phone = clean_mobile(r.get('mother_phone'))
    mother_occ   = str(r.get('mother_occupation', '') or '').strip() or None
    gdn_is       = str(r.get('guardian_is', '') or '').strip() or 'father'
    gdn_name     = str(r.get('guardian_name', '') or '').strip() or None
    gdn_rel      = str(r.get('guardian_relation', '') or '').strip() or None
    gdn_email    = str(r.get('guardian_email', '') or '').strip() or None
    gdn_phone    = clean_mobile(r.get('guardian_phone'))
    gdn_occ      = str(r.get('guardian_occupation', '') or '').strip() or ''
    gdn_addr     = str(r.get('guardian_address', '') or '').strip() or None
    cur_addr     = str(r.get('current_address', '') or '').strip() or None
    perm_addr    = str(r.get('permanent_address', '') or '').strip() or None
    bank_acct    = str(r.get('bank_account_no', '') or '').strip() or None
    bank_name    = str(r.get('bank_name', '') or '').strip() or None
    ifsc         = str(r.get('ifsc_code', '') or '').strip() or None
    aadhaar      = str(r.get('adhar_no', '') or '').strip() or None
    prev_school  = str(r.get('previous_school', '') or '').strip() or None
    regulation_id= str(r.get('regulation_id', '') or '').strip() or None
    emis_num     = str(r.get('emis_num', '') or '').strip() or None
    hsc_reg      = str(r.get('hsc_reg_no', '') or '').strip() or None
    ug_reg       = str(r.get('ug_reg_no', '') or '').strip() or None
    abc_id       = str(r.get('abc_id', '') or '').strip() or None
    father_adhar = str(r.get('father_adhar_no', '') or '').strip() or None
    mother_adhar = str(r.get('mother_adhar_no', '') or '').strip() or None
    migr_cert    = str(r.get('migration_cert_num', '') or '').strip() or None
    medium       = str(r.get('medium', '') or '').strip() or None
    rte          = str(r.get('rte', '') or '').strip() or None
    samagra_id   = str(r.get('samagra_id', '') or '').strip() or None

    if not firstname:
        print(f"  SKIP row with no firstname (adm_no={adm_no})")
        continue

    student_keys.append((adm_no, cls))

    sql(f"-- Student: {firstname} | {cls} | adm={adm_no}")
    sql(f"INSERT INTO students ("
        f"admission_no, roll_no, firstname, middlename, lastname, "
        f"gender, dob, category_id, religion, cast, "
        f"mobileno, email, admission_date, blood_group, "
        f"height, weight, measurement_date, "
        f"father_name, father_phone, father_occupation, "
        f"mother_name, mother_phone, mother_occupation, "
        f"guardian_is, guardian_name, guardian_relation, guardian_email, "
        f"guardian_phone, guardian_occupation, guardian_address, "
        f"current_address, permanent_address, "
        f"bank_account_no, bank_name, ifsc_code, "
        f"adhar_no, father_adhar_no, mother_adhar_no, "
        f"register_no, regulation_id, emis_num, hsc_reg_no, ug_reg_no, "
        f"abc_id, migration_cert_num, medium, samagra_id, rte, "
        f"previous_school, "
        f"is_active, parent_id, dis_note, father_pic, mother_pic, guardian_pic, "
        f"note"
        f")"
        f" SELECT "
        f"{esc(adm_no)}, {esc_null(roll_no)}, {esc(firstname)}, {esc_null(middlename)}, {esc_null(lastname)}, "
        f"{esc(gender)}, {dob}, {esc_null(category_id)}, {esc_null(religion)}, {esc_null(cast_val)}, "
        f"{esc_null(mobileno)}, {esc_null(email)}, {adm_date}, {esc(blood_group)}, "
        f"{esc(height)}, {esc(weight)}, {meas_date}, "
        f"{esc_null(father_name)}, {esc_null(father_phone)}, {esc_null(father_occ)}, "
        f"{esc_null(mother_name)}, {esc_null(mother_phone)}, {esc_null(mother_occ)}, "
        f"{esc(gdn_is)}, {esc_null(gdn_name)}, {esc_null(gdn_rel)}, {esc_null(gdn_email)}, "
        f"{esc_null(gdn_phone)}, {esc(gdn_occ)}, {esc_null(gdn_addr)}, "
        f"{esc_null(cur_addr)}, {esc_null(perm_addr)}, "
        f"{esc_null(bank_acct)}, {esc_null(bank_name)}, {esc_null(ifsc)}, "
        f"{esc_null(aadhaar)}, {esc_null(father_adhar)}, {esc_null(mother_adhar)}, "
        f"{esc_null(reg_no)}, {esc_null(regulation_id)}, {esc_null(emis_num)}, {esc_null(hsc_reg)}, {esc_null(ug_reg)}, "
        f"{esc_null(abc_id)}, {esc_null(migr_cert)}, {esc_null(medium)}, {esc_null(samagra_id)}, {esc_null(rte)}, "
        f"{esc_null(prev_school)}, "
        f"'yes', 0, '', '', '', '', "
        f"{esc(BATCH_TAG)} "
        f"WHERE NOT EXISTS (SELECT 1 FROM students WHERE admission_no={esc(adm_no)});"
    )

sql("")

# ═══════════════════════════════════════════════════════════════════════════════
# 5. STUDENT SESSIONS
# ═══════════════════════════════════════════════════════════════════════════════
sql("-- ── 5. Student sessions ──────────────────────────────────────────────")

unique_classes = sorted(set(cls for _, cls in student_keys))

for cls in unique_classes:
    sec = CLASS_SECTION.get(cls, 'A')
    cls_adm_nos = [adm_no for adm_no, c in student_keys if c == cls]
    sql(f"-- {cls} → section {sec} ({len(cls_adm_nos)} students)")
    sql(f"INSERT INTO student_session (session_id, student_id, class_id, section_id, is_active, is_alumni)")
    sql(f"  SELECT {SESSION_ID}, s.id, cs.class_id, cs.section_id, 'yes', 0")
    sql(f"  FROM students s")
    sql(f"  JOIN classes c ON LOWER(c.class)=LOWER({esc(cls)})")
    sql(f"  JOIN sections sec ON LOWER(sec.section)=LOWER({esc(sec)})")
    sql(f"  JOIN class_sections cs ON cs.class_id=c.id AND cs.section_id=sec.id")
    sql(f"  WHERE s.admission_no IN (")
    sql(f"    {', '.join(esc(a) for a in cls_adm_nos)}")
    sql(f"  )")
    sql(f"  AND NOT EXISTS (")
    sql(f"    SELECT 1 FROM student_session ss2")
    sql(f"    WHERE ss2.session_id={SESSION_ID} AND ss2.student_id=s.id")
    sql(f"  );")
    sql("")

# ═══════════════════════════════════════════════════════════════════════════════
# 6. STUDENT USER ACCOUNTS
# ═══════════════════════════════════════════════════════════════════════════════
sql("-- ── 6. Student user accounts ─────────────────────────────────────────")
sql("INSERT INTO users (user_id, username, password, childs, role, lang_id, currency_id, verification_code, is_active)")
sql(f"SELECT s.id, s.admission_no, 'Welcome@123', '', 'student', {LANG_ID}, {CURRENCY_ID}, '', 'yes'")
sql(f"FROM students s WHERE s.note={esc(BATCH_TAG)}")
sql("AND NOT EXISTS (SELECT 1 FROM users u WHERE u.user_id=s.id AND u.role='student');")
sql("")

sql("-- ── 6b. Parent user accounts ─────────────────────────────────────────")
sql("INSERT INTO users (user_id, username, password, childs, role, lang_id, currency_id, verification_code, is_active)")
sql(f"SELECT s.id, CONCAT('par', s.id), 'Welcome@123', s.id, 'parent', {LANG_ID}, {CURRENCY_ID}, '', 'yes'")
sql(f"FROM students s WHERE s.note={esc(BATCH_TAG)}")
sql("AND NOT EXISTS (SELECT 1 FROM users u WHERE u.username=CONCAT('par', s.id) AND u.role='parent');")
sql("")

sql("-- ── 6c. Set parent_id on students ────────────────────────────────────")
sql("UPDATE students s")
sql("JOIN users u ON u.username=CONCAT('par', s.id) AND u.role='parent'")
sql("SET s.parent_id=u.id")
sql(f"WHERE s.note={esc(BATCH_TAG)};")
sql("")

sql("SET FOREIGN_KEY_CHECKS = 1;")
sql("-- ── End of maptc_import.sql ────────────────────────────────────────────")

# ═══════════════════════════════════════════════════════════════════════════════
# WRITE SQL FILE
# ═══════════════════════════════════════════════════════════════════════════════
with open(OUT_SQL, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')

print(f"SQL file written: {OUT_SQL}")
print(f"  Student rows processed: {len(student_keys)}")
print(f"  Unique classes: {unique_classes}")
print()
print("To deploy:")
PEM  = "/Volumes/WORK/aws ec2 connect/minerva_prod.pem"
HOST = "ec2-user@13.234.255.106"
PASS = "3gw4*86*!zno-EMO"
print(f"  scp -i '{PEM}' {OUT_SQL} {HOST}:/tmp/maptc_import.sql")
print(f"  ssh -i '{PEM}' {HOST} \"mysql -u meenakshi -p'{PASS}' maptc < /tmp/maptc_import.sql\"")

# ── Optionally auto-deploy ────────────────────────────────────────────────────
if '--deploy' in sys.argv:
    print("\nDeploying to EC2...")
    r1 = subprocess.run(['scp', '-i', PEM, '-o', 'StrictHostKeyChecking=no',
                         OUT_SQL, f'{HOST}:/tmp/maptc_import.sql'],
                        capture_output=True, text=True)
    if r1.returncode != 0:
        print("SCP failed:", r1.stderr)
        sys.exit(1)
    print("SCP OK. Running SQL...")
    r2 = subprocess.run(['ssh', '-i', PEM, '-o', 'StrictHostKeyChecking=no', HOST,
                         f"mysql -u meenakshi -p'{PASS}' maptc < /tmp/maptc_import.sql"],
                        capture_output=True, text=True)
    if r2.returncode != 0:
        print("MySQL failed:", r2.stderr)
        sys.exit(1)
    print("Done! MySQL output:", r2.stdout or "(no output = success)")
